FROM node:lts-slim AS builder
WORKDIR /build/
COPY package.json ./
RUN npm install
COPY angular.json tsconfig.json ./
COPY src/ /build/src/
RUN npm run build

FROM nginx:latest
ADD ./deployments/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/dist/talent-web/ /usr/share/nginx/html/
EXPOSE 80
EXPOSE 443 
CMD ["nginx", "-g", "daemon off;"]